package server

import (
	"context"
	"encoding/hex"
	"fmt"
	"log"
	"net"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/crypto/ssh"
	"rssh/internal"
	"rssh/internal/server/data"
	"rssh/internal/server/multiplexer"
	"rssh/internal/server/tcp"
	"rssh/internal/server/tunnels"
	"rssh/internal/server/users"
	"rssh/internal/server/webhooks"
	"rssh/internal/server/webserver"
	"rssh/pkg/mux"
)

type Runtime struct {
	mux  *mux.Multiplexer
	done chan struct{}
}

func (r *Runtime) Done() <-chan struct{} {
	if r == nil {
		ch := make(chan struct{})
		close(ch)
		return ch
	}
	return r.done
}

func (r *Runtime) Stop(ctx context.Context) error {
	if r == nil || r.mux == nil {
		return nil
	}

	type shutdowner interface {
		Shutdown(context.Context) error
	}
	if s, ok := any(r.mux).(shutdowner); ok {
		return s.Shutdown(ctx)
	}

	r.mux.Close()
	return nil
}

func CreateOrLoadServerKeys(privateKeyPath string) (ssh.Signer, error) {

	//If we have already created a private key (or there is one in the current directory) dont overwrite/create another one
	if _, err := os.Stat(privateKeyPath); os.IsNotExist(err) {

		privateKeyPem, err := internal.GeneratePrivateKey()
		if err != nil {
			return nil, fmt.Errorf("unable to generate private key, and no private key specified: %s", err)
		}

		err = os.WriteFile(privateKeyPath, privateKeyPem, 0600)
		if err != nil {
			return nil, fmt.Errorf("unable to write private key to disk: %s", err)
		}
	}

	privateBytes, err := os.ReadFile(privateKeyPath)
	if err != nil {
		return nil, fmt.Errorf("failed to load private key (%s): %s", privateKeyPath, err)
	}

	private, err := ssh.ParsePrivateKey(privateBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to parse private key: %s", err)
	}

	return private, nil
}

func Start(addr, dataDir, connectBackAddress string, autogeneratedConnectBack bool, TLSCertPath, TLSKeyPath string, insecure, enabledDownloads, enabletTLS, openproxy bool, timeout int) (*Runtime, error) {
	c := mux.MultiplexerConfig{
		Control:           true,
		Downloads:         enabledDownloads,
		TLS:               enabletTLS,
		TLSCertPath:       TLSCertPath,
		TLSKeyPath:        TLSKeyPath,
		AutoTLSCommonName: connectBackAddress,
		TcpKeepAlive:      timeout,
		PollingAuthChecker: func(key string, addr net.Addr) bool {

			authorizedKey, err := hex.DecodeString(key)
			if err != nil {
				return false
			}

			pubKey, err := ssh.ParsePublicKey(authorizedKey)
			if err != nil {
				return false
			}

			_, err = CheckAuth(filepath.Join(dataDir, "authorized_controllee_keys"), pubKey, getIP(addr.String()), insecure)
			return err == nil

		},
	}

	privateKeyPath := filepath.Join(dataDir, "id_ed25519")

	log.Println("Version: ", internal.Version)
	var err error
	multiplexer.ServerMultiplexer, err = mux.ListenWithConfig("tcp", addr, c)
	if err != nil {
		return nil, fmt.Errorf("failed to listen on %s (%s)", addr, err)
	}

	log.Printf("Listening on %s\n", addr)

	private, err := CreateOrLoadServerKeys(privateKeyPath)
	if err != nil {
		multiplexer.ServerMultiplexer.Close()
		return nil, err
	}

	log.Printf("Loading private key from: %s\n", privateKeyPath)

	log.Println("Server key fingerprint: ", internal.FingerprintSHA256Hex(private.PublicKey()))

	if enabledDownloads {
		if len(connectBackAddress) == 0 {
			connectBackAddress = addr
		}
		projectRoot := findProjectRoot()
		go webserver.Start(multiplexer.ServerMultiplexer.HTTPDownloadRequests(), connectBackAddress, autogeneratedConnectBack, projectRoot, dataDir, private.PublicKey())
		go tcp.Start(multiplexer.ServerMultiplexer.TCPDownloadRequests())
	}

	err = data.LoadDatabase(filepath.Join(dataDir, "data.db"))
	if err != nil {
		multiplexer.ServerMultiplexer.Close()
		return nil, err
	}

	if err := tunnels.InitAllowlist(dataDir); err != nil {
		log.Println("failed to load tunnel allowlist:", err)
	}

	// Load persisted known clients into in-memory registry so offline hosts survive restarts.
	if err := users.LoadKnownClientsFromDB(); err != nil {
		log.Println("failed to load known clients:", err)
	}

	go webhooks.StartWebhooks()

	rt := &Runtime{
		mux:  multiplexer.ServerMultiplexer,
		done: make(chan struct{}),
	}
	go func() {
		defer close(rt.done)
		if err := StartSSHServer(multiplexer.ServerMultiplexer.ControlRequests(), private, insecure, openproxy, dataDir, timeout); err != nil {
			log.Println("ssh server stopped:", err)
		}
	}()

	return rt, nil
}

func Run(addr, dataDir, connectBackAddress string, autogeneratedConnectBack bool, TLSCertPath, TLSKeyPath string, insecure, enabledDownloads, enabletTLS, openproxy bool, timeout int) {
	rt, err := Start(addr, dataDir, connectBackAddress, autogeneratedConnectBack, TLSCertPath, TLSKeyPath, insecure, enabledDownloads, enabletTLS, openproxy, timeout)
	if err != nil {
		log.Fatal(err)
	}
	<-rt.Done()
}

func findProjectRoot() string {
	// Best-effort discovery of repo root so client builds work regardless of cwd.
	// We search upward for `cmd/client`.
	candidates := []string{}

	if exe, err := os.Executable(); err == nil && exe != "" {
		dir := filepath.Dir(exe)
		candidates = append(candidates, dir)
		candidates = append(candidates, filepath.Dir(dir))
	}
	if cwd, err := os.Getwd(); err == nil && cwd != "" {
		candidates = append(candidates, cwd)
		candidates = append(candidates, filepath.Dir(cwd))
	}

	seen := map[string]bool{}
	for _, base := range candidates {
		base = strings.TrimSpace(base)
		if base == "" || seen[base] {
			continue
		}
		seen[base] = true

		for cur := base; cur != "" && cur != string(filepath.Separator); cur = filepath.Dir(cur) {
			clientDir := filepath.Join(cur, "cmd", "client")
			if fi, err := os.Stat(clientDir); err == nil && fi.IsDir() {
				return cur
			}
			next := filepath.Dir(cur)
			if next == cur {
				break
			}
		}
	}

	// fallback: previous behaviour
	return "../"
}
